##  Hello Mentees

You might me aware about using jupyter notebook.
It's simple to use and way more interactive than other compilers
This writen here is language called Markdown which helps us make it more interactive

To run a code you need to click `Run`.
* Note you can also run the complete file by clicking `Kernel`  

If any given moment your kernel stops responding restart and re-run the code using options from `Kernel`.
You can also run a box by pressing `Shift`+`Enter`

# Week 1

Although week1 only introduction we'll stretch a little to cover it all.

# Numpy

In [1]:
import numpy as np

Numpy is a mathematical library which helps us in most mathematical functions
Before this let's get clarrified with arrays, lists and tupples
#### Difference between Array List and Tuple
### Array
An array is a contiguous memory allocation for data storage of same datatype. The static array always has a predefined size and it is efficient for iterative works as the elements are stored side by side in the dedicated memory locations. It is not that effective when it comes to inserting a new element in between the already present elements.
Similarly, it causes inefficient memory management when you delete an element in between the elements present. 
To avoid the drawbacks of static arrays to a certain extent, the dynamic array was introduced and the data structures like vectors, array list and likewise fall under the dynamic array. These dynamic arrays can be resized, and they can be placed in a scattered manner in the memory space as per availability.

### List
The concept of the dynamic array led to list or linked list as some like to call it. Unlike an array, a linked list is not continuous memory allocation. It has scatted memory allocation technique. Each node of a list consists of two parts. The first part contains the data while the second part is a pointer that had the memory reference of the next node wherever it is placed in the memory. This makes the memory management efficient in all scenarios and you can add or delete nodes in a list effortlessly with extremely high processing speed. Unlike an array, a list can have different data types.

### Tuple
A tuple is an object that can contain heterogeneous data. Out of all data structures, a tuple is the fastest and they consume the least amount of memory. Like a static array, a tuple is fixed in size and that is why tuples are replacing array completely as they are more efficient in all parameters. If you have a dataset which will be assigned only once, and its value should not change again, you need a tuple.


In [2]:
a=[1,2,3]

In [3]:
type(a)

list

In [4]:
b=np.array(a)
type(b)

numpy.ndarray

In [5]:
len(b)

3

In [6]:
a.append(4)
print(a)

[1, 2, 3, 4]


In [7]:
b.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

### Find it out why this error occured?
You can discuss it in the group

In [8]:
a.insert(4,5)
print(a)

[1, 2, 3, 4, 5]


In [9]:
a.insert(0,7)
print(a)

[7, 1, 2, 3, 4, 5]


In [10]:
c=np.array([[1,2],[3,4]])
d=np.array([[2,2]])

### Do refer the pdf shared

In [11]:
type(c)

numpy.ndarray

In [12]:
type(d)

numpy.ndarray

In [13]:
c*d

array([[2, 4],
       [6, 8]])

In [14]:
c**d

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [15]:
np.dot(c,d.T)

array([[ 6],
       [14]])

Adding `.T` takes transpose of the matrix.

In [16]:
np.sum(c)

10

In [17]:
np.log(c)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [18]:
c.max()

4

In [19]:
c.mean()

2.5

#### Do check out more functions
You'll find the library to be easy to use.  
If at any given moment you're stuck,
# Just GOOGLE it

# Pandas

This library is majorly used to deal with dataframes extracted from csv.  
Machine learning is used on a formated datasets.  
Collection of dataset  depends on the source.  
But as Data scientist you must know hoe to sort the data

In [20]:
import pandas as pd

data set source https://www.kaggle.com/geomack/spotifyclassification/downloads/spotifyclassification.zip/1

In [21]:
data=pd.read_csv('data/data.csv')

In [22]:
data

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0              0      0.010200         0.833       204600   0.434   
1              1      0.199000         0.743       326933   0.359   
2              2      0.034400         0.838       185707   0.412   
3              3      0.604000         0.494       199413   0.338   
4              4      0.180000         0.678       392893   0.561   
5              5      0.004790         0.804       251333   0.560   
6              6      0.014500         0.739       241400   0.472   
7              7      0.020200         0.266       349667   0.348   
8              8      0.048100         0.603       202853   0.944   
9              9      0.002080         0.836       226840   0.603   
10            10      0.057200         0.525       358187   0.855   
11            11      0.091500         0.753       324880   0.748   
12            12      0.253000         0.603       356973   0.434   
13            13      0.366000         0.762       243270   0.476   
14            14      0.440000         0.662       247288   0.603   
15            15      0.019000         0.637       188333   0.832   
16            16      0.023900         0.603       270827   0.955   
17            17      0.233000         0.789       447907   0.659   
18            18      0.314000         0.713       195429   0.611   
19            19      0.024200         0.735       214347   0.759   
20            20      0.000702         0.854       249253   0.719   
21            21      0.000240         0.747       307680   0.740   
22            22      0.118000         0.854       287086   0.401   
23            23      0.000596         0.224       132760   0.925   
24            24      0.279000         0.512       203400   0.564   
25            25      0.002190         0.781       205160   0.795   
26            26      0.341000         0.411       199500   0.684   
27            27      0.018000         0.646       188333   0.837   
28            28      0.051600         0.782       228562   0.572   
29            29      0.282000         0.735       186096   0.400   
...          ...           ...           ...          ...     ...   
1987        1987      0.028300         0.421       175907   0.831   
1988        1988      0.000084         0.467       209187   0.794   
1989        1989      0.000797         0.480       222053   0.826   
1990        1990      0.000590         0.594       218720   0.858   
1991        1991      0.000366         0.544       245133   0.788   
1992        1992      0.007490         0.446       241253   0.881   
1993        1993      0.001900         0.551       195280   0.732   
1994        1994      0.510000         0.630       240000   0.772   
1995        1995      0.020200         0.333       174240   0.913   
1996        1996      0.003630         0.743       259889   0.889   
1997        1997      0.000870         0.465       265600   0.953   
1998        1998      0.031600         0.680       211853   0.725   
1999        1999      0.004990         0.619       245656   0.949   
2000        2000      0.093500         0.520       231667   0.809   
2001        2001      0.002620         0.484       224320   0.609   
2002        2002      0.030100         0.583       224092   0.891   
2003        2003      0.000461         0.562       201031   0.960   
2004        2004      0.096900         0.595       198400   0.975   
2005        2005      0.021600         0.526       216072   0.825   
2006        2006      0.178000         0.501       202839   0.683   
2007        2007      0.002170         0.639       296276   0.978   
2008        2008      0.054100         0.646       160408   0.714   
2009        2009      0.004990         0.595       224000   0.837   
2010        2010      0.002310         0.624       206013   0.971   
2011        2011      0.000586         0.528       245053   0.879   
2012        2012      0.001060         0.584       274404   0.932   
2013

In [23]:
#print first 5 rows
data.head()

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0           0        0.0102         0.833       204600   0.434   
1           1        0.1990         0.743       326933   0.359   
2           2        0.0344         0.838       185707   0.412   
3           3        0.6040         0.494       199413   0.338   
4           4        0.1800         0.678       392893   0.561   

   instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
0          0.021900    2    0.1650    -8.795     1       0.4310  150.062   
1          0.006110    1    0.1370   -10.401     1       0.0794  160.083   
2          0.000234    2    0.1590    -7.148     1       0.2890   75.044   
3          0.510000    5    0.0922   -15.236     1       0.0261   86.468   
4          0.512000    5    0.4390   -11.648     0       0.0694  174.004   

   time_signature  valence  target      song_title            artist  
0             4.0    0.286       1        Mask Off            Future  
1             4.0    0.588       1         Redbone  Childish Gambino  
2             4.0    0.173       1    Xanny Family            Future  
3             4.0    0.230       1  Master Of None       Beach House  
4             4.0    0.904       1  Parallel Lines       Junior Boys

In [24]:
data.describe()

Unnamed: 0  acousticness  danceability   duration_ms       energy  \
count  2017.000000   2017.000000   2017.000000  2.017000e+03  2017.000000   
mean   1008.000000      0.187590      0.618422  2.463062e+05     0.681577   
std     582.402066      0.259989      0.161029  8.198181e+04     0.210273   
min       0.000000      0.000003      0.122000  1.604200e+04     0.014800   
25%     504.000000      0.009630      0.514000  2.000150e+05     0.563000   
50%    1008.000000      0.063300      0.631000  2.292610e+05     0.715000   
75%    1512.000000      0.265000      0.738000  2.703330e+05     0.846000   
max    2016.000000      0.995000      0.984000  1.004627e+06     0.998000   

       instrumentalness          key     liveness     loudness         mode  \
count       2017.000000  2017.000000  2017.000000  2017.000000  2017.000000   
mean           0.133286     5.342588     0.190844    -7.085624     0.612295   
std            0.273162     3.648240     0.155453     3.761684     0.487347   
min            0.000000     0.000000     0.018800   -33.097000     0.000000   
25%            0.000000     2.000000     0.092300    -8.394000     0.000000   
50%            0.000076     6.000000     0.127000    -6.248000     1.000000   
75%            0.054000     9.000000     0.247000    -4.746000     1.000000   
max            0.976000    11.000000     0.969000    -0.307000     1.000000   

       speechiness        tempo  time_signature      valence       target  
count  2017.000000  2017.000000     2017.000000  2017.000000  2017.000000  
mean      0.092664   121.603272        3.968270     0.496815     0.505702  
std       0.089931    26.685604        0.255853     0.247195     0.500091  
min       0.023100    47.859000        1.000000     0.034800     0.000000  
25%       0.037500   100.189000        4.000000     0.295000     0.000000  
50%       0.054900   121.427000        4.000000     0.492000     1.000000  
75%       0.108000   137.849000        4.000000     0.691000     1.000000  
max       0.816000   219.331000        5.000000     0.992000     1.000000

In [25]:
# transfering acousticness column to different dataset
data1=data["acousticness"]
data1.head()

0    0.0102
1    0.1990
2    0.0344
3    0.6040
4    0.1800
Name: acousticness, dtype: float64

In [26]:
data1.mean()

0.18759003442241004

In [27]:
data.groupby(['mode']).sum()
# over here we've grouped the data on the basis of Modes the sum parameter adds all the other columns

Unnamed: 0  acousticness  danceability  duration_ms    energy  \
mode                                                                  
0         753558    129.318399       491.179    198636806  547.5090   
1        1279578    249.050701       756.178    298162794  827.2321   

      instrumentalness   key  liveness  loudness  speechiness       tempo  \
mode                                                                        
0           112.307261  4877  152.0789 -5378.287      76.8281   96666.741   
1           156.529650  5899  232.8535 -8913.417     110.0757  148607.058   

      time_signature   valence  target  
mode                                    
0             3113.0  396.4947     431  
1             4891.0  605.5812     589

In [28]:
data.groupby(['mode']).mean()
# over here we've grouped the data on the basis of Modes the sum parameter mean all the other columns

Unnamed: 0  acousticness  danceability    duration_ms    energy  \
mode                                                                     
0      963.629156      0.165369      0.628106  254011.260870  0.700139   
1     1036.095547      0.201660      0.612290  241427.363563  0.669824   

      instrumentalness       key  liveness  loudness  speechiness       tempo  \
mode                                                                            
0             0.143615  6.236573  0.194474 -6.877605     0.098246  123.614758   
1             0.126745  4.776518  0.188545 -7.217342     0.089130  120.329602   

      time_signature   valence    target  
mode                                      
0           3.980818  0.507026  0.551151  
1           3.960324  0.490349  0.476923

All the major SQL commands can also be performed on the dataset
There is a method called magic box sql that allows us to change dataset using sql commands
You can learn more from https://www.geeksforgeeks.org/python-pandas-dataframe/