So guys major part of week 2 includes reading  
here are rest of the stuffs  

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("data/Data.csv")
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

if you've a look at the dataset you see we have missing values and you know hoe to deal with it  
there are also new methods which I'll guide you through

In [3]:
data1 = data.dropna(how='any',axis=0) 
data1.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes

continuing th preprocessing do keep in mind ML require mathematics, so we cannot have words  
to solve this we need to convert them to numbers.  
we can do it by giving them numbers like
* France 0
* Germany 1
* Spain 2

In [4]:
#converting data frame to values
X = data1.iloc[:, :-1].values
y = data1.iloc[:, 3].values

In [5]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [6]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()

In [8]:
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [0, 35.0, 58000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

* France 0
* Germany 1
* Spain 2

In [9]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [10]:
y

array([0, 1, 0, 0, 1, 1, 0, 1])

* no 0
* yes 1

over here i'll point out that in case of countries we shall not give weightage  to countries  
due to this spain will get importance but not france  
think it over or google what will happen if instead of 3 we'll have 100 countries!!

to over come this we use one hot encoding

In [11]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder(categories='auto')   
p = onehotencoder.fit_transform(X[:,0:1]).toarray()

# this right over here is for column 0
#actually it means 0-1 but in python larger value is not inc

In [12]:
p

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

now column one is 1 for values country is france and so on  
# Google dummy variable trap



you can also do this encoding using pandas as well

In [13]:
data_new=pd.get_dummies(data1["Country"])
data_new

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
5       1        0      0
7       1        0      0
8       0        1      0
9       1        0      0

In [14]:
dff=pd.concat([data_new, data1["Age"],data1["Salary"]], axis=1)
dff

France  Germany  Spain   Age   Salary
0       1        0      0  44.0  72000.0
1       0        0      1  27.0  48000.0
2       0        1      0  30.0  54000.0
3       0        0      1  38.0  61000.0
5       1        0      0  35.0  58000.0
7       1        0      0  48.0  79000.0
8       0        1      0  50.0  83000.0
9       1        0      0  37.0  67000.0

## Do google dummy variable trap and make relevant changes above

# Normalisation
in the data frame above we should scale down the salary and age   
because with respect to 1 and 0 it is too large and will neglect the relevance of country

In [15]:
X = dff.iloc[:,:].values
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X[:,3:5] = sc_X.fit_transform(X[:,3:5])

In [16]:
X

array([[ 1.        ,  0.        ,  0.        ,  0.69985807,  0.58989097],
       [ 0.        ,  0.        ,  1.        , -1.51364653, -1.50749915],
       [ 0.        ,  1.        ,  0.        , -1.12302807, -0.98315162],
       [ 0.        ,  0.        ,  1.        , -0.08137885, -0.37141284],
       [ 1.        ,  0.        ,  0.        , -0.47199731, -0.6335866 ],
       [ 1.        ,  0.        ,  0.        ,  1.22068269,  1.20162976],
       [ 0.        ,  1.        ,  0.        ,  1.48109499,  1.55119478],
       [ 1.        ,  0.        ,  0.        , -0.211585  ,  0.1529347 ]])

### Last but not the least what if we don't want to shorten our data by removing unknown values
maybe we take mean ?

In [17]:
print(X)

[[ 1.          0.          0.          0.69985807  0.58989097]
 [ 0.          0.          1.         -1.51364653 -1.50749915]
 [ 0.          1.          0.         -1.12302807 -0.98315162]
 [ 0.          0.          1.         -0.08137885 -0.37141284]
 [ 1.          0.          0.         -0.47199731 -0.6335866 ]
 [ 1.          0.          0.          1.22068269  1.20162976]
 [ 0.          1.          0.          1.48109499  1.55119478]
 [ 1.          0.          0.         -0.211585    0.1529347 ]]


In [18]:
X = data.iloc[:,:].values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy='mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [19]:
#lets print x again MEAN
print(X)

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 63777.77777777778 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' 38.77777777777778 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]


In [20]:
X = data.iloc[:,:].values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy='median')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [21]:
#lets print x again MEDIAN
print(X)

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 61000.0 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' 38.0 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]


## do look into the syllabus and complete the rest reading from google